#!/bin/sh
# Builds the single-file version of the template:
#   Scripts/*.lua (in load order) -> dist/CivilMissionTemplate.lua
# Run from the repository root after editing anything in Scripts/.
set -e
cd "$(dirname "$0")/.."
mkdir -p dist
OUT=dist/CivilMissionTemplate.lua

{
  echo "----------------------------------------------------------------------"
  echo "-- DCS Civil Mission Template — single-file build"
  echo "-- Generated by tools/build.sh from the files in Scripts/."
  echo "-- Do not edit this file directly: edit Scripts/ and rebuild."
  echo "-- Load with a single DO SCRIPT FILE action at MISSION START."
  echo "----------------------------------------------------------------------"
  for f in Scripts/01_CivilCore.lua \
           Scripts/10_CivilFirefighting.lua \
           Scripts/20_CivilRescue.lua \
           Scripts/30_CivilPolice.lua \
           Scripts/40_CivilTransport.lua; do
    echo ""
    echo "-- ===================================================================="
    echo "-- >>> $f"
    echo "-- ===================================================================="
    cat "$f"
  done
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines)"
